export const SPEEDTEST_SERVERS = [
  {
    id: 1,
    name: 'Amsterdam',
    server: 'https://am3-speedtest.tools.gcore.com/',
    country: 'nl',
    region: 'eu', // TODO add everywhere
    dlURL: 'speedtest-backend/garbage.php',
    ulURL: 'speedtest-backend/empty.php',
    pingURL: 'speedtest-backend/empty.php',
    getIpURL: 'speedtest-backend/getIP.php',
  },
  {
    id: 2,
    name: 'Frankfurt',
    server: 'https://fr5-speedtest.tools.gcore.com/',
    country: 'de',
    dlURL: 'speedtest-backend/garbage.php',
    ulURL: 'speedtest-backend/empty.php',
    pingURL: 'speedtest-backend/empty.php',
    getIpURL: 'speedtest-backend/getIP.php',
  },
  {
    id: 3,
    name: 'London',
    server: 'https://thn2-speedtest.tools.gcore.com/',
    country: 'uk',
    dlURL: 'speedtest-backend/garbage.php',
    ulURL: 'speedtest-backend/empty.php',
    pingURL: 'speedtest-backend/empty.php',
    getIpURL: 'speedtest-backend/getIP.php',
  },
  {
    id: 4,
    name: 'Paris',
    server: 'https://pa5-speedtest.tools.gcore.com/',
    country: 'fr',
    dlURL: 'speedtest-backend/garbage.php',
    ulURL: 'speedtest-backend/empty.php',
    pingURL: 'speedtest-backend/empty.php',
    getIpURL: 'speedtest-backend/getIP.php',
  },
  {
    id: 5,
    name: 'Warsaw',
    server: 'https://pl1-speedtest.tools.gcore.com/',
    country: 'pl',
    dlURL: 'speedtest-backend/garbage.php',
    ulURL: 'speedtest-backend/empty.php',
    pingURL: 'speedtest-backend/empty.php',
    getIpURL: 'speedtest-backend/getIP.php',
  },
  {
    id: 6,
    name: 'Los Angeles',
    server: 'https://la2-speedtest.tools.gcore.com/',
    country: 'us',
    dlURL: 'speedtest-backend/garbage.php',
    ulURL: 'speedtest-backend/empty.php',
    pingURL: 'speedtest-backend/empty.php',
    getIpURL: 'speedtest-backend/getIP.php',
  },
  {
    id: 7,
    name: 'Minneapolis',
    server: 'https://min4-speedtest.tools.gcore.com/',
    country: 'us',
    dlURL: 'speedtest-backend/garbage.php',
    ulURL: 'speedtest-backend/empty.php',
    pingURL: 'speedtest-backend/empty.php',
    getIpURL: 'speedtest-backend/getIP.php',
  },
  {
    id: 8,
    name: 'New York',
    server: 'https://ny2-speedtest.tools.gcore.com/',
    country: 'us',
    dlURL: 'speedtest-backend/garbage.php',
    ulURL: 'speedtest-backend/empty.php',
    pingURL: 'speedtest-backend/empty.php',
    getIpURL: 'speedtest-backend/getIP.php',
  },
  {
    id: 9,
    name: 'Seattle',
    server: 'https://wbs-speedtest.tools.gcore.com/',
    country: 'us',
    dlURL: 'speedtest-backend/garbage.php',
    ulURL: 'speedtest-backend/empty.php',
    pingURL: 'speedtest-backend/empty.php',
    getIpURL: 'speedtest-backend/getIP.php',
  },
  {
    id: 10,
    name: 'Buenos Aires',
    server: 'https://syt-speedtest.tools.gcore.com/',
    country: 'ar',
    dlURL: 'speedtest-backend/garbage.php',
    ulURL: 'speedtest-backend/empty.php',
    pingURL: 'speedtest-backend/empty.php',
    getIpURL: 'speedtest-backend/getIP.php',
  },
  {
    id: 11,
    name: 'Santiago de Querétaro',
    server: 'https://sqr-speedtest.tools.gcore.com/',
    country: 'mx',
    dlURL: 'speedtest-backend/garbage.php',
    ulURL: 'speedtest-backend/empty.php',
    pingURL: 'speedtest-backend/empty.php',
    getIpURL: 'speedtest-backend/getIP.php',
  },
  {
    id: 12,
    name: 'São Paulo',
    server: 'https://sp3-speedtest.tools.gcore.com/',
    country: 'br',
    dlURL: 'speedtest-backend/garbage.php',
    ulURL: 'speedtest-backend/empty.php',
    pingURL: 'speedtest-backend/empty.php',
    getIpURL: 'speedtest-backend/getIP.php',
  },
  {
    id: 13,
    name: 'Dubai',
    server: 'https://eti-speedtest.tools.gcore.com/',
    country: 'ae',
    dlURL: 'speedtest-backend/garbage.php',
    ulURL: 'speedtest-backend/empty.php',
    pingURL: 'speedtest-backend/empty.php',
    getIpURL: 'speedtest-backend/getIP.php',
  },
  {
    id: 14,
    name: 'Istanbul',
    server: 'https://tii-speedtest.tools.gcore.com/',
    country: 'tr',
    dlURL: 'speedtest-backend/garbage.php',
    ulURL: 'speedtest-backend/empty.php',
    pingURL: 'speedtest-backend/empty.php',
    getIpURL: 'speedtest-backend/getIP.php',
  },
  {
    id: 15,
    name: 'Tel Aviv',
    server: 'https://bzi-speedtest.tools.gcore.com/',
    country: 'il',
    dlURL: 'speedtest-backend/garbage.php',
    ulURL: 'speedtest-backend/empty.php',
    pingURL: 'speedtest-backend/empty.php',
    getIpURL: 'speedtest-backend/getIP.php',
  },
  {
    id: 16,
    name: 'Almaty',
    server: 'https://kal-speedtest.tools.gcore.com/',
    country: 'kz',
    dlURL: 'speedtest-backend/garbage.php',
    ulURL: 'speedtest-backend/empty.php',
    pingURL: 'speedtest-backend/empty.php',
    getIpURL: 'speedtest-backend/getIP.php',
  },
  {
    id: 17,
    name: 'Bangkok',
    server: 'https://tidc-speedtest.tools.gcore.com/',
    country: 'th',
    dlURL: 'speedtest-backend/garbage.php',
    ulURL: 'speedtest-backend/empty.php',
    pingURL: 'speedtest-backend/empty.php',
    getIpURL: 'speedtest-backend/getIP.php',
  },
  {
    id: 18,
    name: 'Hong Kong',
    server: 'https://hk2-speedtest.tools.gcore.com/',
    country: 'hk',
    dlURL: 'speedtest-backend/garbage.php',
    ulURL: 'speedtest-backend/empty.php',
    pingURL: 'speedtest-backend/empty.php',
    getIpURL: 'speedtest-backend/getIP.php',
  },
  {
    id: 19,
    name: 'Mumbai',
    server: 'https://ww-speedtest.tools.gcore.com/',
    country: 'in',
    dlURL: 'speedtest-backend/garbage.php',
    ulURL: 'speedtest-backend/empty.php',
    pingURL: 'speedtest-backend/empty.php',
    getIpURL: 'speedtest-backend/getIP.php',
  },
  {
    id: 20,
    name: 'Seoul',
    server: 'https://kx-speedtest.tools.gcore.com/',
    country: 'kr',
    dlURL: 'speedtest-backend/garbage.php',
    ulURL: 'speedtest-backend/empty.php',
    pingURL: 'speedtest-backend/empty.php',
    getIpURL: 'speedtest-backend/getIP.php',
  },
  {
    id: 21,
    name: 'Singapore',
    server: 'https://sg1-speedtest.tools.gcore.com/',
    country: 'sg',
    dlURL: 'speedtest-backend/garbage.php',
    ulURL: 'speedtest-backend/empty.php',
    pingURL: 'speedtest-backend/empty.php',
    getIpURL: 'speedtest-backend/getIP.php',
  },
  {
    id: 22,
    name: 'Sydney',
    server: 'https://sy4-speedtest.tools.gcore.com/',
    country: 'au',
    dlURL: 'speedtest-backend/garbage.php',
    ulURL: 'speedtest-backend/empty.php',
    pingURL: 'speedtest-backend/empty.php',
    getIpURL: 'speedtest-backend/getIP.php',
  },
  {
    id: 23,
    name: 'Tokyo',
    server: 'https://cc1-speedtest.tools.gcore.com/',
    country: 'jp',
    dlURL: 'speedtest-backend/garbage.php',
    ulURL: 'speedtest-backend/empty.php',
    pingURL: 'speedtest-backend/empty.php',
    getIpURL: 'speedtest-backend/getIP.php',
  },
  {
    id: 24,
    name: 'Cairo',
    server: 'https://teg-speedtest.tools.gcore.com/',
    country: 'eg',
    dlURL: 'speedtest-backend/garbage.php',
    ulURL: 'speedtest-backend/empty.php',
    pingURL: 'speedtest-backend/empty.php',
    getIpURL: 'speedtest-backend/getIP.php',
  },
  {
    id: 25,
    name: 'Johannesburg',
    server: 'https://jp1-speedtest.tools.gcore.com/',
    country: 'za',
    dlURL: 'speedtest-backend/garbage.php',
    ulURL: 'speedtest-backend/empty.php',
    pingURL: 'speedtest-backend/empty.php',
    getIpURL: 'speedtest-backend/getIP.php',
  },
  {
    id: 26,
    name: 'Lagos',
    server: 'https://lgs-speedtest.tools.gcore.com/',
    country: 'ng',
    dlURL: 'speedtest-backend/garbage.php',
    ulURL: 'speedtest-backend/empty.php',
    pingURL: 'speedtest-backend/empty.php',
    getIpURL: 'speedtest-backend/getIP.php',
  },
]
